name:                diary-parser
version:             0.1.0.0
github:              "tobytripp/diary-parser"
license:             EPL
author:              "Toby Tripp"
maintainer:          "toby.tripp@gmail.com"
copyright:           "2023 Toby Tripp"

extra-source-files:
- README.org

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/tobytripp/diary-parser#readme>

dependencies:
- base >= 4.7 && < 5
- text >= 2.0.2
- parsec >= 3.1.11

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  diary-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diary-parser

tests:
  diary-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - diary-parser
    - HUnit
